### ISSUE TITLE
eido link and fishing dont work anymore! Please help!

### ISSUE THREAD

**Issue by Kumasfvn** [nyaThoi/nEShit#10]
![image](https://user-images.githubusercontent.com/21078243/205424897-df515b66-fa13-4391-a655-cacd2b3042d5.png)
i used this file
![image](https://user-images.githubusercontent.com/21078243/205424928-2dacac39-d668-4718-bec2-b4beb95c184b.png)

**Comment by nyaThoi** [comment]
u dont inject into ur game right.

On the next Update im adding the Messagebox of inject failed.

**Comment by Kumasfvn** [comment]
how to inject into my game right please!!

**Comment by nyaThoi** [comment]
Start nEShit.exe, show on ur CMD it say the Number of ur Client game process, enter the number, done.

> how to inject into my game right please!!

**Comment by Kumasfvn** [comment]
i did what you said but nothing happen. I open the game, run nEShit.exe, press 0 (i have try 1 also) then enter, but it remains the same.

**Comment by nyaThoi** [comment]
Show me ur CMD from nEShit.exe

**Comment by Kumasfvn** [comment]
> Show me ur CMD from nEShit.exe

here it is
![image](https://user-images.githubusercontent.com/21078243/205796582-77d177b9-969c-4450-93f1-034840805aae.png)

**Comment by xSatella** [comment]
my cheat can't work too
