### ISSUE TITLE
nEShit does not work any more pls help

### ISSUE THREAD

**Issue by Nyoka-c** [nyaThoi/nEShit#11]
I injected but none of the functions are working

**Comment by nyaThoi** [comment]
> > > I injected but none of the functions are working
> > 
> > 
> > Show me ur Console.
> 
> ![image](https://user-images.githubusercontent.com/121477913/212076194-0ea91877-b9e2-4ef6-a6f4-53294369a492.png) here it is

u didnt enter ur Game Process, insert on ur console 12284 and press enter.

**Comment by Nyoka-c** [comment]
> > > > I injected but none of the functions are working
> > > 
> > > 
> > > Show me ur Console.
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/121477913/212076194-0ea91877-b9e2-4ef6-a6f4-53294369a492.png) here it is
> 
> u didnt enter ur Game Process, insert on ur console 12284 and press enter.

i started game, opened nEShit, pressed game PID then pressed enter twice (because pressed enter 1 time does not show anything) but nothing happened

**Comment by nyaThoi** [comment]
> > > > > I injected but none of the functions are working
> > > > 
> > > > 
> > > > Show me ur Console.
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/121477913/212076194-0ea91877-b9e2-4ef6-a6f4-53294369a492.png) here it is
> > 
> > 
> > u didnt enter ur Game Process, insert on ur console 12284 and press enter.
> 
> i started game, opened nEShit, pressed game PID then pressed enter twice (because pressed enter 1 time does not show anything) but nothing happened

Start nEShit.exe as Admin.
- Enter 5 or any Number (not 1) for default Client
Now u can see the Gameprocess, if not the Game doenst Start.
- Enter 12284
Now it injected into the game process id 12284. (12284 its not the fix ID !!!!!)

**Comment by Nyoka-c** [comment]
> > > > > > I injected but none of the functions are working
> > > > > 
> > > > > 
> > > > > Show me ur Console.
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/121477913/212076194-0ea91877-b9e2-4ef6-a6f4-53294369a492.png) here it is
> > > 
> > > 
> > > u didnt enter ur Game Process, insert on ur console 12284 and press enter.
> > 
> > 
> > i started game, opened nEShit, pressed game PID then pressed enter twice (because pressed enter 1 time does not show anything) but nothing happened
> 
> Start nEShit.exe as Admin.
> 
> * Enter 5 or any Number (not 1) for default Client
>   Now u can see the Gameprocess, if not the Game doenst Start.
> * Enter 12284
>   Now it injected into the game process id 12284. (12284 its not the fix ID !!!!!)

![image](https://user-images.githubusercontent.com/121477913/212533575-b9e13128-8a97-48db-9040-70cdbd732dd7.png)
sadly it said this :((

**Comment by nyaThoi** [comment]
> > > > > > > I injected but none of the functions are working
> > > > > > 
> > > > > > 
> > > > > > Show me ur Console.
> > > > > 
> > > > > 
> > > > > ![image](https://user-images.githubusercontent.com/121477913/212076194-0ea91877-b9e2-4ef6-a6f4-53294369a492.png) here it is
> > > > 
> > > > 
> > > > u didnt enter ur Game Process, insert on ur console 12284 and press enter.
> > > 
> > > 
> > > i started game, opened nEShit, pressed game PID then pressed enter twice (because pressed enter 1 time does not show anything) but nothing happened
> > 
> > 
> > Start nEShit.exe as Admin.
> > 
> > * Enter 5 or any Number (not 1) for default Client
> >   Now u can see the Gameprocess, if not the Game doenst Start.
> > * Enter 12284
> >   Now it injected into the game process id 12284. (12284 its not the fix ID !!!!!)
> 
> ![image](https://user-images.githubusercontent.com/121477913/212533575-b9e13128-8a97-48db-9040-70cdbd732dd7.png) sadly it said this :((

The Error Message of MyMemory u ignore the Readme.
![image](https://user-images.githubusercontent.com/57547293/212534105-4755ab1b-eec2-49bf-8757-c55800de36f9.png)

Install Microsoft Visual C++ 2010 Redistributable Package (x86) to fix it.

**Comment by Nyoka-c** [comment]
> > > > > > > > I injected but none of the functions are working
> > > > > > > 
> > > > > > > 
> > > > > > > Show me ur Console.
> > > > > > 
> > > > > > 
> > > > > > ![image](https://user-images.githubusercontent.com/121477913/212076194-0ea91877-b9e2-4ef6-a6f4-53294369a492.png) here it is
> > > > > 
> > > > > 
> > > > > u didnt enter ur Game Process, insert on ur console 12284 and press enter.
> > > > 
> > > > 
> > > > i started game, opened nEShit, pressed game PID then pressed enter twice (because pressed enter 1 time does not show anything) but nothing happened
> > > 
> > > 
> > > Start nEShit.exe as Admin.
> > > 
> > > * Enter 5 or any Number (not 1) for default Client
> > >   Now u can see the Gameprocess, if not the Game doenst Start.
> > > * Enter 12284
> > >   Now it injected into the game process id 12284. (12284 its not the fix ID !!!!!)
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/121477913/212533575-b9e13128-8a97-48db-9040-70cdbd732dd7.png) sadly it said this :((
> 
> If u get the Error Message of MyMemory, u have ignore the Readme. ![image](https://user-images.githubusercontent.com/57547293/212534105-4755ab1b-eec2-49bf-8757-c55800de36f9.png)
> 
> Install Microsoft Visual C++ 2010 Redistributable Package (x86) to fix it.

thank you so much!!!! it works now. Wish you all the best <3
