### ISSUE TITLE
nEShit not responding!

### ISSUE THREAD

**Issue by Kumasfvn** [nyaThoi/nEShit#12]
Hi the game has just updated and nEShit cannot run anymore. Please update. Thank you so much!
![image](https://user-images.githubusercontent.com/21078243/217068179-9654923a-df30-474e-9dd3-95b733d0a827.png)

**Comment by Nyoka-c** [comment]
:( Pls update

**Comment by nyaThoi** [comment]
Sorry, no ETA for Fix.

**Comment by nyaThoi** [comment]
https://github.com/nyaThoi/nEShit/releases/tag/1.0.0.0
