### ISSUE TITLE
Everything done as per your instructions, but not working. 

### ISSUE THREAD

**Issue by IkuSenpai** [nyaThoi/nEShit#13]
I know I know, you're going to say to do X, but so far I followed every direction you said to others in all of the previous issues. I have used your tools in the past with absolutely no issue, and I am not seeing a reason as to why it's not working anymore. 

![1](https://user-images.githubusercontent.com/28810005/221378464-061f2297-55e3-4434-bd5d-8574dd6e4fac.png)

Before I figured out it was PID I was literally trying ant number as your tool stated. Obviously didn't work. Then I did PID. I was, expecting it to like in the past, to automatically hook to the game. It didn't so I just pressed the enter key as there was no indication of it "working" until nEShit popped up. However, no option seems to do anything. Auto Link isn't auto talking/linking. Speedhack isn't sonic'ing, & Fishing assistant isn't assisting. 

I have **all** .NET frameworks installed & all MV C++ Packages installed (I am a developer).

**Comment by Nyoka-c** [comment]
> I know I know, you're going to say to do X, but so far I followed every direction you said to others in all of the previous issues. I have used your tools in the past with absolutely no issue, and I am not seeing a reason as to why it's not working anymore.
> 
> ![1](https://user-images.githubusercontent.com/28810005/221378464-061f2297-55e3-4434-bd5d-8574dd6e4fac.png)
> 
> Before I figured out it was PID I was literally trying ant number as your tool stated. Obviously didn't work. Then I did PID. I was, expecting it to like in the past, to automatically hook to the game. It didn't so I just pressed the enter key as there was no indication of it "working" until nEShit popped up. However, no option seems to do anything. Auto Link isn't auto talking/linking. Speedhack isn't sonic'ing, & Fishing assistant isn't assisting.
> 
> I have **all** .NET frameworks installed & all MV C++ Packages installed (I am a developer).

type any number except 1, enter, type PID, enter.

**Comment by IkuSenpai** [comment]
Ty I fixed it by editing something else.
