### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by xSatella** [nyaThoi/nEShit#7]
i already know how to run this, but the cheat not work(?)
![Capture](https://user-images.githubusercontent.com/94574304/172083694-547f360b-9f41-4c06-8ee0-8e8bcec92808.JPG)
![Capture1](https://user-images.githubusercontent.com/94574304/172083749-3a488dc9-f528-4bb9-b11e-e410695428d3.JPG)

**Comment by xSatella** [comment]
i already know how to run this cheat, but

**Comment by Kumasfvn** [comment]
hi how to used this please. 
![image](https://user-images.githubusercontent.com/21078243/205424544-ff0e9a2e-36f1-40ec-bcda-e12d4430ab3b.png)
